### ISSUE TITLE
Failure occurred. Do you want to cleanup by removing ...

### ISSUE THREAD

**Issue by Hiieu** [nephila/djangocms-installer#161]
I did exactly everything in tutorial and I got this error after typing:

`Failure occurred. Do you want to cleanup by removing \path\myproject? [Y/N]`

```
C:\Users\HP\Dropbox\venv\portfolio5\blabla>djangocms -p . my_demo
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]: 3.0
Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 1.7
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: English
Optional default time zone [default America/Chicago]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
Use custom template set [default no]:
Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]:
Failure occurred. Do you want to cleanup by removing C:\Users\HP\Dropbox\venv\portfolio5\blabla? [Y/N] 
```

And when I typ Y I get this:

```
Traceback (most recent call last):
  File "C:\Users\HP\Dropbox\venv\portfolio4\env\Scripts\djangocms-script.py", line 9, in <module>
    load_entry_point('djangocms-installer==0.7.1.post1', 'console_scripts', 'djangocms')()
  File "C:\Users\HP\Dropbox\venv\portfolio4\env\lib\site-packages\djangocms_installer\main.py", line 30, in execute
    django.create_project(config_data)
  File "C:\Users\HP\Dropbox\venv\portfolio4\env\lib\site-packages\djangocms_installer\django\__init__.py", line 43, in create_project
    subprocess.check_call(['django-admin.py', 'startproject'] + args)
  File "C:\Python27\Lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\Lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\Lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by Hiieu** [comment]
@yakky: I think my issue is a duplicate 

https://github.com/nephila/djangocms-installer/issues/160

**Comment by Hiieu** [comment]
@yakky: Well I found an alternative. I installed django cms on my ubuntu system then copied all folder to my windows project directory and now it works.

**Comment by yakky** [comment]
@Hiieu  would you please check by installing https://github.com/nephila/djangocms-installer/archive/feature/hotfixes.zip?

**Comment by kanishpatel** [comment]
Getting the same issue on OSX 10.10 with python 2.7.6 in a virtualenv

tried the hotfix, It now prints a couple of extra lines before failing.

    (my_env):tutorial-project $ djangocms -p . mysite
    Database configuration (in URL format) [default sqlite://localhost/project.db]:
    django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]:
    Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 1.6
    Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
    Install and configure reversion support (choices: yes, no) [default yes]:
    Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en,de
    Optional default time zone [default America/Chicago]:
    Activate Django timezone support (choices: yes, no) [default yes]:
    Activate CMS permission management (choices: yes, no) [default yes]:
    Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
    Use custom template set [default no]:
    Load a starting page with examples after installation. Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes

    Creating the project
    Please wait while I install dependencies
    Dependencies installed
    Creating the projectFailure occurred. Do you want to cleanup by removing...

**Comment by yakky** [comment]
what happends after answering?

**Comment by kanishpatel** [comment]
Ok so I apologise, mine was a completely different issue, nothing to do with djangocms-installer. 

Pressing Y complained that pillow wasn't installed or something is wrong with it, but it was installed, and it could find libjpeg (and the rest). Turns out (after a lot of digging) that upgrading OSX to Yosemite had ruined my homebrew setup and I had a bunch of broken symlinks. Fixed those and now everything works with the djangocms-installer version installed with pip.

Sorry about that.

**Comment by yakky** [comment]
@kanishpatel no worries :)

**Comment by duyutaochn** [comment]
我也遇上了一样的问题，把python 虚拟环境文件夹目录下面的lib文件夹内的东西全删了就不再出现了

**Comment by lwmonster** [comment]
I have the same problem,  what is the final solution?

**Comment by yakky** [comment]
@lwmonster use djangocms-installer with ``--verbose`` option to get more information why the installation fails

**Comment by lwmonster** [comment]
@yakky   with this command:  djangocms -f -p . --verbose mysite 
I got this error:
```
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "񐁂򐁇N": syntax error
Failure occurred.
```
But 
```
import sqlite3
```
in python is good.

**Comment by yakky** [comment]
which python version / OS are you using?
What's the database connection string do you provide?

**Comment by lwmonster** [comment]
@yakky 
python 2.7.11
CentOS release 6.6 (Final)

DB string is default:
Database configuration (in URL format) [default sqlite://localhost/project.db]:
detailed message:
```
# djangocms  -f -p . --verbose mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]:
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, stable) [default stable]:
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: zh-cn
Optional default time zone [default local]: Asia/Shanghai
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]:
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]:
Creating the project
Please wait while I install dependencies
Package install command: install django-cms<3.3 django-treebeard>=2.0 https://github.com/divio/djangocms-column/archive/master.zip?1453083013.71 https://github.com/divio/djangocms-googlemap/archive/master.zip?1453083013.71 https://github.com/divio/djangocms-inherit/archive/master.zip?1453083013.71 https://github.com/divio/djangocms-link/archive/master.zip?1453083013.71 https://github.com/divio/djangocms-style/archive/master.zip?1453083013.71 easy_thumbnails django-filer>=0.9.12 cmsplugin-filer>=0.10.2 djangocms-admin-style>=1.0.6 djangocms-text-ckeditor>=2.8.0 Django<1.9 pytz django-reversion>=1.8.7,<1.9 django-classy-tags>=0.3.4.1 html5lib Pillow>=2.3 django-sekizai>=0.7 six
Collecting https://github.com/divio/djangocms-column/archive/master.zip?1453083013.71
  Downloading https://github.com/divio/djangocms-column/archive/master.zip?1453083013.71 (164kB)
Collecting https://github.com/divio/djangocms-googlemap/archive/master.zip?1453083013.71
  Downloading https://github.com/divio/djangocms-googlemap/archive/master.zip?1453083013.71 (234kB)
Collecting https://github.com/divio/djangocms-inherit/archive/master.zip?1453083013.71
  Downloading https://github.com/divio/djangocms-inherit/archive/master.zip?1453083013.71 (171kB)
Collecting https://github.com/divio/djangocms-link/archive/master.zip?1453083013.71
  Downloading https://github.com/divio/djangocms-link/archive/master.zip?1453083013.71 (195kB)
Collecting https://github.com/divio/djangocms-style/archive/master.zip?1453083013.71
  Downloading https://github.com/divio/djangocms-style/archive/master.zip?1453083013.71 (146kB)
Collecting django-cms<3.3
Collecting django-treebeard>=2.0
Collecting easy-thumbnails
  Using cached easy_thumbnails-2.3-py2.py3-none-any.whl
Collecting django-filer>=0.9.12
  Using cached django_filer-1.0.6-py2.py3-none-any.whl
Collecting cmsplugin-filer>=0.10.2
  Using cached cmsplugin_filer-1.0.1-py2.py3-none-any.whl
Collecting djangocms-admin-style>=1.0.6
  Using cached djangocms_admin_style-1.0.8-py2.py3-none-any.whl
Collecting djangocms-text-ckeditor>=2.8.0
Collecting Django<1.9
  Using cached Django-1.8.8-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pytz in /home/liangwei/django-cms-env/lib/python2.7/site-packages
Collecting django-reversion<1.9,>=1.8.7
Collecting django-classy-tags>=0.3.4.1
  Using cached django_classy_tags-0.7.0-py2.py3-none-any.whl
Collecting html5lib
Collecting Pillow>=2.3
Collecting django-sekizai>=0.7
  Using cached django_sekizai-0.9.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /home/liangwei/django-cms-env/lib/python2.7/site-packages
Collecting django-select2<5.0,>=4.3 (from djangocms-link==1.7.1)
Collecting django-formtools>=1.0 (from django-cms<3.3)
  Using cached django_formtools-1.0-py2.py3-none-any.whl
Collecting Unidecode<0.05,>=0.04 (from django-filer>=0.9.12)
Collecting django-mptt<0.9,>=0.6 (from django-filer>=0.9.12)
  Using cached django_mptt-0.8.0-py2.py3-none-any.whl
Collecting django-polymorphic<0.9,>=0.7 (from django-filer>=0.9.12)
  Using cached django_polymorphic-0.8.1-py2.py3-none-any.whl
Collecting django-appconf (from cmsplugin-filer>=0.10.2)
  Using cached django_appconf-1.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/liangwei/django-cms-env/lib/python2.7/site-packages (from django-polymorphic<0.9,>=0.7->django-filer>=0.9.12)
Installing collected packages: Django, django-classy-tags, django-sekizai, django-treebeard, django-formtools, djangocms-admin-style, html5lib, django-cms, Pillow, easy-thumbnails, Unidecode, django-mptt, django-polymorphic, django-filer, django-appconf, cmsplugin-filer, djangocms-text-ckeditor, django-reversion, djangocms-column, djangocms-googlemap, djangocms-inherit, django-select2, djangocms-link, djangocms-style
  Running setup.py install for djangocms-column
  Running setup.py install for djangocms-googlemap
  Running setup.py install for djangocms-inherit
  Running setup.py install for djangocms-link
  Running setup.py install for djangocms-style
Successfully installed Django-1.8.8 Pillow-3.1.0 Unidecode-0.4.18 cmsplugin-filer-1.0.1 django-appconf-1.0.1 django-classy-tags-0.7.0 django-cms-3.2.0 django-filer-1.0.6 django-formtools-1.0 django-mptt-0.8.0 django-polymorphic-0.8.1 django-reversion-1.8.7 django-sekizai-0.9.0 django-select2-4.3.2 django-treebeard-4.0 djangocms-admin-style-1.0.8 djangocms-column-1.6.0 djangocms-googlemap-0.4.0 djangocms-inherit-0.1.1 djangocms-link-1.7.1 djangocms-style-1.6.0 djangocms-text-ckeditor-2.8.1 easy-thumbnails-2.3 html5lib-0.9999999
Dependencies installed
Creating the project
Project creation command: /home/liangwei/django-cms-env/bin/python /home/liangwei/django-cms-env/bin/django-admin.py startproject mysite .
Database setup commands: /home/liangwei/django-cms-env/bin/python -W ignore manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    with self.connection.schema_editor() as editor:
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 85, in __enter__
    self.atomic.__enter__()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/transaction.py", line 183, in __enter__
    connection._start_transaction_under_autocommit()
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 299, in _start_transaction_under_autocommit
    self.cursor().execute("BEGIN")
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/liangwei/django-cms-env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "񐁂򐁇N": syntax error
Failure occurred.
```

**Comment by lwmonster** [comment]
@yakky  I have Googled for several days, can't find the answer......

**Comment by yakky** [comment]
@lwmonster what's the console encoding / language / locale?

**Comment by lwmonster** [comment]
@yakky 

```
# echo $LANG
zh_CN.UTF-8


```

**Comment by yakky** [comment]
@lwmonster could you try launching ``LANG='en_US.UTF-8' djangocms  -f -p . --verbose mysite``
I'd bet it's an encoding issue, given the output ``"񐁂򐁇N"`` looks suspicious

**Comment by lwmonster** [comment]
Still the same error ......
