### ISSUE TITLE
errors during creating new project

### ISSUE THREAD

**Issue by Mirodil** [nephila/djangocms-installer#165]
here is error:
```

(env) E:\Python\demo>cd tutorial-project

(env) E:\Python\demo\tutorial-project>djangocms -p . mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]:
sqlite://localhost/project.db
django CMS version (choices: 2.4, 3.0, stable, develop) [default stable]: stable

Django version (choices: 1.4, 1.5, 1.6, 1.7, stable) [default stable]: 1.6
Activate Django I18N / L10N setting (choices: yes, no) [default yes]: yes
Install and configure reversion support (choices: yes, no) [default yes]: yes
Languages to enable. Option can be provided multiple times, or as a comma separa
ted list. Only language codes supported by Django can be used here: en,ru
Optional default time zone [default America/Chicago]:
Activate Django timezone support (choices: yes, no) [default yes]: yes
Activate CMS permission management (choices: yes, no) [default yes]: yes
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
Use custom template set [default no]: no
Load a starting page with examples after installation. Choose "no" if you use a
custom template set. (choices: yes, no) [default no]: yes
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectTraceback (most recent call last):
  File "E:\Python\demo\env\Scripts\django-admin.py", line 2, in <module>
    from django.core import management
ImportError: No module named django.core
Failure occurred. Do you want to cleanup by removing E:\Python\demo\tutorial-pro
ject? [Y/N] N
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\Python\demo\env\Scripts\djangocms.exe\__main__.py", line 9, in <modul
e>
  File "E:\Python\demo\env\lib\site-packages\djangocms_installer\main.py", line
32, in execute
    django.create_project(config_data)
  File "E:\Python\demo\env\lib\site-packages\djangocms_installer\django\__init__
.py", line 44, in create_project
    shell=True)
  File "C:\Python27\Lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'django-admin.py startproject mysite .' r
eturned non-zero exit status 1

(env) E:\Python\demo\tutorial-project>
```

**Comment by yakky** [comment]
@Mirodil are you using latest version on pypi (0.7.2)?

**Comment by Mirodil** [comment]
yes. the issue has been fxied.
