### ISSUE TITLE
Python3.2 sys.stderr.write unicode

### ISSUE THREAD

**Issue by alvaromlg** [nephila/djangocms-installer#169]
Hello, there is this traceback ocurring with python3.2

Traceback (most recent call last):
  File "/usr/local/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.7.2', 'console_scripts', 'djangocms')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.2/dist-packages/djangocms_installer/main.py", line 8, in <module>
    from . import config, django, install
  File "/usr/local/lib/python3.2/dist-packages/djangocms_installer/config/__init__.py", line 101
    sys.stderr.write(u"Project name '%s' is not a valid app name, "
SyntaxError: invalid syntax

It's solved if the 'u' is removed, is it maybe an issue compatibility which just happens when the project's name is not valid?

**Comment by yakky** [comment]
Python 3.2 is not supported by django-cms  and djangocms-installer, you must upgrade to python 3.3
