### ISSUE TITLE
I can not create the project

### ISSUE THREAD

**Issue by tormenta1026** [nephila/djangocms-installer#178]
I can not create the project follow the steps in the quick installation and I could not install it by any means.

http://docs.django-cms.org/en/support-3.0.x/introduction/install.html

This is the message I get:

Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectFailure occurred. Do you want to cleanup by removing /home/user/testing? [Y/N]

I use Debian.

I need help.

**Comment by yakky** [comment]
@tormenta1026 any other messages/tracebacks? have you checked installer FAQ http://djangocms-installer.readthedocs.org/en/latest/faq.html?
Which were the input you provided to the wizard?

**Comment by giovannicode** [comment]
I too have had the same issue. I get the same message. I don't get a traceback  unless I answer 'yes' to removing the project.

Then I get the following traceback: 

```
Removing everything under /home/vagrant/virtual_env
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 31, in execute
    install.check_install(config_data)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 56, in check_install
    raise EnvironmentError("\n".join(errors))
OSError: Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/venv/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 57, in execute
    "http://djangocms-installer.rtfd.org\n" % e).with_traceback(tb)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 31, in execute
    install.check_install(config_data)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 56, in check_install
    raise EnvironmentError("\n".join(errors))
OSError: Pillow is not compiled with JPEG support, see 'Libraries installation issues' documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html
Documentation available at http://djangocms-installer.rtfd.org
```

I have tried several different ways of installing the project. With python 3.4 and python 2.7, with a virtualenv, with pyenv, without a virtual environment, but I still can't get it to work.

**Comment by yakky** [comment]
@giovannicode have you checked that pillow can be built with jpeg support?

**Comment by tormenta1026** [comment]
There is another way to create Project ?

**Comment by yakky** [comment]
@tormenta1026 you could try to use the dump mode to get the requirements, create the virtualenv and install dependencies with pip

**Comment by giovannicode** [comment]
I checked for JPEG support and it turns out pillow did not have it.
So, based on this StackOverflow [question](http://stackoverflow.com/questions/8915296/python-image-library-fails-with-message-decoder-jpeg-not-available-pil), I recompiled it with JPEG support. 

Now I get a little bit further, but then I get this error message:
```
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectTraceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 30, in <module>
    from pysqlite2 import dbapi2 as Database
ImportError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 32, in <module>
    from sqlite3 import dbapi2 as Database
  File "/home/vagrant/.pyenv/versions/3.4.0/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/vagrant/.pyenv/versions/3.4.0/lib/python3.4/sqlite3/dbapi2.py", line 26, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

**Comment by yakky** [comment]
This looks like an error in the local python library installation. it does not look like a regular virtualenv setup

**Comment by yakky** [comment]
Closing this due to missing feedback. Feel free to reopen if you have further information
