### ISSUE TITLE
CalledProcessError while pip install

### ISSUE THREAD

**Issue by sedrubal** [nephila/djangocms-installer#215]
I tried to install djangocms with the djangocms-installer but it always failes. Tested on `fedora:22` and `ubuntu:14.04` with `python3` and `python2`. After answering the questions it takes some time and then this messages appear:

```python
Please wait while I install dependencies
Command "/srv/venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ywunetca/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-dd_zxv3n-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv/include/site/python3.4/Pillow" failed with error code 1 in /tmp/pip-build-ywunetca/Pillow
Failure occurred. Do you want to cleanup by removing /srv/cms? [Y/N] y
Removing everything under /srv/cms
Traceback (most recent call last):
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 33, in execute
    config_data.requirements, config_data.pip_options
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 90, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '-q', 'django-cms<3.2', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-admin-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-column/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-flash/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-link/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-text-ckeditor/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-file/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-picture/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-video/archive/master.zip?1446510328.1703925', 'Django<1.8', 'pytz', 'django-reversion>=1.8.2,<1.8.6', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/venv/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 64, in execute
    'http://djangocms-installer.rtfd.org\n' % e).with_traceback(tb)
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 33, in execute
    config_data.requirements, config_data.pip_options
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 90, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
OSError: Command '['pip', 'install', '-q', 'django-cms<3.2', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-admin-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-column/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-flash/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-link/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-style/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-text-ckeditor/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-file/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-picture/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1446510328.1703925', 'https://github.com/divio/djangocms-video/archive/master.zip?1446510328.1703925', 'Django<1.8', 'pytz', 'django-reversion>=1.8.2,<1.8.6', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1
Documentation available at http://djangocms-installer.rtfd.org
```

**Comment by yakky** [comment]
@sedrubal  Could you test the "verbose" branch providing --verbose option on the command line?

**Comment by sedrubal** [comment]
I found out that  `djangocms-installer` installs `Pillow` and `Pillow` has [dependencies](https://pillow.readthedocs.org/en/3.0.x/installation.html#linux-installation), I have not installed. For fedora this is `python-devel` or `python3-devel`:

```
libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel
```

Additionally one need `gcc` to install Pillow which isn't documented on their [docs](https://pillow.readthedocs.org) - grml.

Please add a section to the [README](https://github.com/nephila/djangocms-installer#installation) and the docs. It's very annoying when everybody has to find out himself.

Without installing the dependencies I get this `--verbose` output:

```python
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow
  Complete output from command /srv/venv/bin/python3 -c "import setuptools;__file__='/tmp/pip-build-vcqt58s5/Pillow/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpts49uv8gpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.4
  creating build/lib.linux-x86_64-3.4/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/features.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/Image.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/TarIO.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/FontFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/__init__.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/_util.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/_binary.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.4/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.4/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-3.4/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vcqt58s5/Pillow/setup.py", line 767, in <module>
      zip_safe=not debug_build(),
    File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/srv/venv/lib/python3.4/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.4/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-vcqt58s5/Pillow/setup.py", line 515, in build_extensions
      % (f, f))
  ValueError: --enable-jpeg requested but jpeg not found, aborting.
  
  ----------------------------------------
  Failed building wheel for Pillow
Failed to build Pillow
Installing collected packages: Pillow, djangocms-text-ckeditor, django-reversion, djangocms-column, djangocms-googlemap, djangocms-inherit, django-select2, djangocms-link, djangocms-style, djangocms-file, djangocms-picture, djangocms-teaser, djangocms-video
  Running setup.py install for Pillow
    Complete output from command /srv/venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-vcqt58s5/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-szfm04dn-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv/include/site/python3.4/Pillow:
    running install
    running build
    running build_py
    running egg_info
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    writing top-level names to Pillow.egg-info/top_level.txt
    writing Pillow.egg-info/PKG-INFO
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vcqt58s5/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/srv/venv/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-vcqt58s5/Pillow/setup.py", line 515, in build_extensions
        % (f, f))
    ValueError: --enable-jpeg requested but jpeg not found, aborting.
    
    ----------------------------------------
Command "/srv/venv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-vcqt58s5/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-szfm04dn-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv/include/site/python3.4/Pillow" failed with error code 1 in /tmp/pip-build-vcqt58s5/Pillow
Traceback (most recent call last):
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 35, in execute
    verbose=config_data.verbose
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 94, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', 'django-cms<3.3', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-column/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-link/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-style/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-file/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-picture/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-video/archive/master.zip?1449931574.2803962', 'djangocms-admin-style>=1.0.6', 'djangocms-text-ckeditor>=2.8.0', 'Django<1.9', 'pytz', 'django-reversion>=1.8.7,<1.9', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/venv/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.8.3.post1', 'console_scripts', 'djangocms')()
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 66, in execute
    'http://djangocms-installer.rtfd.org\n' % e).with_traceback(tb)
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/main.py", line 35, in execute
    verbose=config_data.verbose
  File "/srv/venv/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 94, in requirements
    subprocess.check_call(['pip'] + args)
  File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
OSError: Command '['pip', 'install', 'django-cms<3.3', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-column/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-link/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-style/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-file/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-picture/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-teaser/archive/master.zip?1449931574.2803962', 'https://github.com/divio/djangocms-video/archive/master.zip?1449931574.2803962', 'djangocms-admin-style>=1.0.6', 'djangocms-text-ckeditor>=2.8.0', 'Django<1.9', 'pytz', 'django-reversion>=1.8.7,<1.9', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1
Documentation available at http://djangocms-installer.rtfd.org
```

While I wrote this documentation right now (which should be obviously your job ;) ) I got a strange error, which I unfortunately could reproduce easily: After configuring and after djangocms-installer installed all dependencies I got this message:

```
Successfully installed Django-1.8.7 Pillow-3.0.0 django-classy-tags-0.7.0 django-cms-3.2.0 django-reversion-1.8.7 django-treebeard-3.0 djangocms-admin-style-1.0.7 djangocms-text-ckeditor-2.8.0 html5lib-0.9999999 pytz-2015.7
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/djangocms_installer/main.py", line 38, in execute
    install.check_install(config_data)
  File "/usr/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 77, in check_install
    raise EnvironmentError('\n'.join(errors))
OSError: Pillow is not installed check for installation errors and see "Libraries installation issues" documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.8.3.post1', 'console_scripts', 'djangocms')()
  File "/usr/lib/python3.4/site-packages/djangocms_installer/main.py", line 66, in execute
    'http://djangocms-installer.rtfd.org\n' % e).with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/djangocms_installer/main.py", line 38, in execute
    install.check_install(config_data)
  File "/usr/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 77, in check_install
    raise EnvironmentError('\n'.join(errors))
OSError: Pillow is not installed check for installation errors and see "Libraries installation issues" documentation section: http://djangocms-installer.readthedocs.org/en/latest/libraries.html
Documentation available at http://djangocms-installer.rtfd.org
```

I was in the virtual envrionment I created before. Running outside the venv worked...

A tip for writing a proper documentation: Use docker or something else and test your documentation step by step using all big Linux distributions. There aren't many packages preinstalled and so you can verify if all dependencies are documented.

**Comment by yakky** [comment]
@sedrubal it's documented https://github.com/nephila/djangocms-installer#caveats and http://djangocms-installer.readthedocs.org/en/latest/libraries.html in more details
I welcome any contribution regarding the correct library naming in all major distributions :)

**Comment by sedrubal** [comment]
Ah ok... I don't have time to contribute and I don't know Restructured Text well... But please link `libraries` in `README`-installation section like this:

"Before using djangocms-installer verify you have all required libraries installed. See libraries for more info"

**Comment by sedrubal** [comment]
Thanks ;)
