### ISSUE TITLE
Error when make new project

### ISSUE THREAD

**Issue by JimyRyan** [nephila/djangocms-installer#220]
Hello,

I try making a new django cms project using the djangocms-installer (0.8.3) but this one crash :(

I'm using : 
* OS : RHEL 6.7 (Cloud Plateforme OpenShift)
* Python 3.3.2
* Djangocms 3.2.0
* Django 1.8.7

I try many options but all the time the installer exit with this error : **ImportError: cannot import name urllib_parse**

Bellow, you can watch the error log : 
```bash
(venv) [.... www]\> djangocms -f -p . djangocms
Database configuration (in URL format) [default sqlite://localhost/project.db]:
django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]:
Django version (choices: 1.5, 1.6, 1.7, 1.8, stable) [default stable]:
Activate Django I18N / L10N setting (choices: yes, no) [default yes]:
Install and configure reversion support (choices: yes, no) [default yes]:
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: fr,en
Optional default time zone [default Europe/Paris]:
Activate Django timezone support (choices: yes, no) [default yes]:
Activate CMS permission management (choices: yes, no) [default yes]:
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: yes
Use custom template set [default no]:
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: yes
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the projectTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/python33/root/usr/lib64/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1586, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1567, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1534, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/djangocms_text_ckeditor/models.py", line 13, in <module>
    from .html import clean_html, extract_images
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
  File "/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/lib/python3.3/site-packages/html5lib/sanitizer.py", line 5, in <module>
    from six.moves import urllib_parse as urlparse
ImportError: cannot import name urllib_parse
Failure occurred. Do you want to cleanup by removing /var/lib/openshift/565827d47628e15f80000030/app-root/runtime/repo/www? [Y/N]
```

**Comment by yakky** [comment]
@JimyRyan could you provide the version of six, html5lib and ckeditor that has been installed in this environment?

**Comment by JimyRyan** [comment]
@yakky I'm using versions : 
* six : I don't know (it's installed automaticly by pip 
```remote: Requirement already satisfied (use --upgrade to upgrade): six in /opt/rh/python33/root/usr/lib/python3.3/site-packages (from djangocms-installer->-r /var/lib/openshift/565827d47628e15f80000030/app-root/runtime/repo/requirements.txt (line 4))```
* html5lib : 0.9999999
* ckeditor : 2.8.0

I don't install custom version, It's a clean install : I only install the required dependencies

**Comment by yakky** [comment]
@JimyRyan I cannot reproduce this issue. Maybe the virtualenv is created with ``--system-site-packages`` option? six should not be in ``/opt/rh/python33/root/usr/lib/python3.3/site-packages`` but in the virtualenv in ``/var/lib/openshift/565827d47628e15f80000030/python/virtenv/venv/``

**Comment by JimyRyan** [comment]
@yakky Hello, I setup an dev environment based on the same code and installed software, I have no problem ! I think, the trouble is with OpenShift... But where ?

**Comment by JimyRyan** [comment]
@yakky I have setup a fresh development environment and I'm surprise to see that the installer work well on a similar OpenShift config.

I think the trouble is due to OpenShift environment, but I don't know what.

Have an nice day

**Comment by yakky** [comment]
Thanks for the update. I don't have an openshift environment to check the original report, though :(
