### ISSUE TITLE
Display pip traceback if errors during install

### ISSUE THREAD

**Issue by sephii** [nephila/djangocms-installer#232]
If you try to run the installer on a fresh Debian LXC you'll get the following error:

```
Failure occurred. Do you want to cleanup by removing /root/blah? [Y/N] 
Traceback (most recent call last):
  File "/root/env/lib/python3.4/site-packages/djangocms_installer/main.py", line 35, in execute
    verbose=config_data.verbose
  File "/root/env/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 94, in requirements
    output = subprocess.check_output(['pip'] + args)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['pip', 'install', '-q', 'django-cms<3.3', 'django-treebeard>=2.0', 'https://github.com/divio/djangocms-column/archive/master.zip?1451649699.4322', 'https://github.com/divio/djangocms-googlemap/archive/master.zip?1451649699.4322', 'https://github.com/divio/djangocms-inherit/archive/master.zip?1451649699.4322', 'https://github.com/divio/djangocms-link/archive/master.zip?1451649699.4322', 'https://github.com/divio/djangocms-style/archive/master.zip?1451649699.4322', 'easy_thumbnails', 'django-filer>=0.9.12', 'cmsplugin-filer>=0.10.2', 'djangocms-admin-style>=1.0.6', 'djangocms-text-ckeditor>=2.8.0', 'Django<1.9', 'pytz', 'django-reversion>=1.8.7,<1.9', 'django-classy-tags>=0.3.4.1', 'html5lib', 'Pillow>=2.3', 'django-sekizai>=0.7', 'six']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/root/env/lib/python3.4/site-packages/djangocms_installer/main.py", line 62, in execute
    install.cleanup_directory(config_data)
  File "/root/env/lib/python3.4/site-packages/djangocms_installer/install/__init__.py", line 125, in cleanup_directory
    if strtobool(choice) or config_data.noinput:
  File "/usr/lib/python3.4/distutils/util.py", line 317, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value ''
```
There are 2 things here:
* There's no default choice to the last question, causing the installer to raise an exception
* The `pip` failure comes from the fact that there were some libs missing that prevented the installation of Pillow (`libjpeg-dev zlib1g-dev python3-dev gcc`) and these are correctly reported when trying to run `pip install Pillow` but are hidden in the error reported by the installer. It would be really great if the installer could give the full pip traceback

**Comment by yakky** [comment]
@sephii for n.2 the new ``--verbose`` option in 0.8.4 should provide the required output. I'll check issue n.1
