### ISSUE TITLE
Installer sets wrong settings for DATABASES for sqlite

### ISSUE THREAD

**Issue by zanderle** [nephila/djangocms-installer#234]
The installer sets the `DATABASES` dictionary slightly wrong for sqlite.

It sets

```python
DATABASES = {
    'default': {
        'CONN_MAX_AGE': '0',
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}
```

instead of 

```python
DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}
```

`CONN_MAX_AGE` value should be an integer, not a string.

The problem seems to be [here](https://github.com/nephila/djangocms-installer/blob/d4899ad4cbed89b4c82c411241e38ac031472ee8/djangocms_installer/django/__init__.py#L371)

The exception that follows this mistake (after running djangocms command):

```bash
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/Users/zanderle/.virtualenvs/cms-test/lib/python2.7/site-packages/django/db/backends/base/base.py", line 114, in connect
    self.close_at = None if max_age is None else time.time() + max_age
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

Thanks to @jarshwah for helping to pinpoint the problem.

**Comment by yakky** [comment]
@zanderle @jarshwah thanks for reporting this. Linked PR should fix the issue
