### ISSUE TITLE
cant create djangocms project on ubuntu aws

### ISSUE THREAD

**Issue by decemer** [nephila/djangocms-installer#245]
cant create djangocms project on ubuntu aws
when i use"djangocms -f -p . mysite",it show
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 131, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: asia/shanghai
The installation failed.
Do you want to clean up by removing /home/ubuntu/tutorial-project?
        Warning: this will delete all files in:
                /home/ubuntu/tutorial-project
Do you want to cleanup? [y/N] y
Removing everything under /home/ubuntu/tutorial-project
**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/home/ubuntu/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/home/ubuntu/env/local/lib/python2.7/site-packages/djangocms_installer/django/__init__.py", line 425, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ubuntu/env/bin/python', u'-W', u'ignore', u'manage.py', u'migrate']' returned non-zero exit status 1`
```
any other same issue too,thx

**Comment by yakky** [comment]
Could you provide the full list of options you input in the wizard?

**Comment by decemer** [comment]
```
Last login: Mon Mar  7 06:13:00 2016 from 202.105.56.130
ubuntu@ip-172-31-26-184:~$ cd tutorial-project                                          
ubuntu@ip-172-31-26-184:~/tutorial-project$ pip install djangocms-installer
Requirement already satisfied (use --upgrade to upgrade): djangocms-installer in /usr/local/lib/python2.7/dist-packages
Cleaning up...
ubuntu@ip-172-31-26-184:~/tutorial-project$ djangocms -f -p . mysite
Database configuration (in URL format) [default sqlite://localhost/project.db]: 
django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]: 
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, stable) [default stable]: 
Activate Django I18N / L10N setting (choices: yes, no) [default yes]: 
Install and configure reversion support (choices: yes, no) [default yes]: 
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en,cn
Optional default time zone [default Etc/UTC]: 
Activate Django timezone support (choices: yes, no) [default yes]: 
Activate CMS permission management (choices: yes, no) [default yes]: 
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: y
Use custom template set [default no]: 
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: y
Creating the project
Please wait while I install dependencies
Dependencies installed
Creating the project
/usr/bin/python: can't open file '/usr/bin/django-admin.py': [Errno 2] No such file or directory
The installation failed.
Do you want to clean up by removing /home/ubuntu/tutorial-project?
        Warning: this will delete all files in:
                /home/ubuntu/tutorial-project
Do you want to cleanup? [y/N] y
Removing everything under /home/ubuntu/tutorial-project


**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/usr/local/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/djangocms_installer/main.py", line 37, in execute
    django.create_project(config_data)
  File "/usr/local/lib/python2.7/dist-packages/djangocms_installer/django/__init__.py", line 46, in create_project
    output = subprocess.check_output(cmd_args, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '/usr/bin/python /usr/bin/django-admin.py startproject mysite .' returned non-zero exit status 2

```

**Comment by yakky** [comment]
@decemer they apparently are two different errors. As stated in the documentation and the readme (https://github.com/nephila/djangocms-installer#warning) installer requires django-admin and python executable in the same directory, which is the default when using virtualenvs, which is the only supported way to install djangocms-installer

**Comment by decemer** [comment]
okay,i have success in dafult setting,thank you

**Comment by yakky** [comment]
You're welcome :)
