### ISSUE TITLE
Attempt to install on Ubuntu 14.04 LTS fails inexplicably

### ISSUE THREAD

**Issue by mkoistinen** [nephila/djangocms-installer#248]
A user "mcjack" reported this on IRC, but didn't seem to want to open a ticket here, or provide a trace. So, I went to Digital Ocean and created a VPS. This is a brand new instance of a server. I first updated apt-get, then did a dist-upgrade, then the rest follows:
````
root@djangocms-installer-test:/var/www# djangocms -p quicktest quicktest
Database configuration (in URL format) [default sqlite://localhost/project.db]: 
django CMS version (choices: 2.4, 3.0, 3.1, 3.2, stable, develop) [default stable]: 
Django version (choices: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, stable) [default stable]: 
Activate Django I18N / L10N setting (choices: yes, no) [default yes]: 
Install and configure reversion support (choices: yes, no) [default yes]: 
Languages to enable. Option can be provided multiple times, or as a comma separated list. Only language codes supported by Django can be used here: en, de
Optional default time zone [default America/New_York]: 
Activate Django timezone support (choices: yes, no) [default yes]: 
Activate CMS permission management (choices: yes, no) [default yes]: 
Use Twitter Bootstrap Theme (choices: yes, no) [default no]: 
Use custom template set [default no]: 
Load a starting page with examples after installation (english language only). Choose "no" if you use a custom template set. (choices: yes, no) [default no]: 
Creating the project
Please wait while I install dependencies


**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/usr/local/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/djangocms_installer/main.py", line 33, in execute
    verbose=config_data.verbose
  File "/usr/local/lib/python2.7/dist-packages/djangocms_installer/install/__init__.py", line 93, in requirements
    output = subprocess.check_output(['pip'] + args)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'pip', u'install', u'-q', u'django-cms<3.3', u'django-treebeard>=2.0', u'https://github.com/divio/djangocms-column/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-googlemap/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-inherit/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-link/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-style/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-file/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-picture/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-teaser/archive/master.zip?1461082015.2', u'https://github.com/divio/djangocms-video/archive/master.zip?1461082015.2', u'djangocms-admin-style>=1.0.6', u'djangocms-text-ckeditor>=2.8.1', u'Django<1.9', u'pytz', u'django-reversion>=1.8.7,<1.9', u'django-classy-tags>=0.3.4.1', u'html5lib', u'Pillow>=2.3', u'django-sekizai>=0.7', u'six']' returned non-zero exit status 1
````

**Comment by yakky** [comment]
I can't reproduce this
Have you installed binary libraries (http://djangocms-installer.readthedocs.org/en/latest/libraries.html#debian-ubuntu) after initial setup?

**Comment by mkoistinen** [comment]
I did not, and I'd bet that was the same issue that the IRC-OP had.
