### ISSUE TITLE
Falls when trying to get localzone from tzlocal

### ISSUE THREAD

**Issue by jeltoesolnce** [nephila/djangocms-installer#265]
Hello. I can't run djangocms -p . my_demo: I get such error

(test)[jeltoesolnce@twin ~/data/www]% djangocms -p . my_demo
Traceback (most recent call last):
  File "/usr/home/jeltoesolnce/.virtualenvs/test/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_installer/main.py", line 15, in execute
    config_data = config.parse(sys.argv[1:])
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_installer/config/__init__.py", line 42, in parse
    required=False, default=get_localzone(),
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/tzlocal/unix.py", line 122, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/tzlocal/unix.py", line 61, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
(test)[jeltoesolnce@twin ~/data/www]%

**Comment by yakky** [comment]
@jeltoesolnce which is your local timezone as reported by your system tools?

**Comment by yakky** [comment]
@jeltoesolnce could you please try https://github.com/nephila/djangocms-installer/archive/hotfix/timezone.zip branch?

**Comment by yakky** [comment]
Fixed in #266

**Comment by jeltoesolnce** [comment]
I did it:

Please wait while I install dependencies
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_text_ckeditor/models.py", line 13, in <module>
    from .html import clean_html, extract_images
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
ImportError: cannot import name sanitizer
The installation failed.
Do you want to clean up by removing /usr/home/jeltoesolnce/data/www/tests_1?
	Warning: this will delete all files in:
		/usr/home/jeltoesolnce/data/www/tests_1
Do you want to cleanup? [y/N] y 
Removing everything under /usr/home/jeltoesolnce/data/www/tests_1


**********************************************************

Check documentation at http://djangocms-installer.rtfd.org

**********************************************************

Traceback (most recent call last):
  File "/usr/home/jeltoesolnce/.virtualenvs/test/bin/djangocms", line 9, in <module>
    load_entry_point('djangocms-installer==0.8.10', 'console_scripts', 'djangocms')()
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_installer-0.8.10-py2.7.egg/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/usr/home/jeltoesolnce/.virtualenvs/test/lib/python2.7/site-packages/djangocms_installer-0.8.10-py2.7.egg/djangocms_installer/django/__init__.py", line 425, in setup_database
    output = subprocess.check_output(command, env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/home/jeltoesolnce/.virtualenvs/test/bin/python', u'-W', u'ignore', u'manage.py', u'migrate']' returned non-zero exit status 1
(test) [jeltoesolnce@twin ~/data/www]% v.lssitepackages 
Django-1.8.13.dist-info
Django_Select2-4.3.2.dist-info
PIL
Pillow-3.3.0.dist-info
Unidecode-0.4.19.dist-info
_markerlib
appconf
argparse-1.4.0-py2.7.egg
classytags
cms
cmsplugin_filer-1.1.2.dist-info
cmsplugin_filer_file
cmsplugin_filer_folder
cmsplugin_filer_image
cmsplugin_filer_link
cmsplugin_filer_teaser
cmsplugin_filer_tests_shared
cmsplugin_filer_utils
cmsplugin_filer_video
dj_database_url-0.4.1-py2.7.egg
django
django_appconf-1.0.2.dist-info
django_classy_tags-0.7.2.dist-info
django_cms-3.2.5.dist-info
django_filer-1.2.4.dist-info
django_formtools-1.0.dist-info
django_mptt-0.8.4.dist-info
django_polymorphic-0.8.1.dist-info
django_reversion-1.8.7.dist-info
django_sekizai-0.9.0.dist-info
django_select2
django_treebeard-4.0.1.dist-info
djangocms_admin_style
djangocms_admin_style-1.2.3.dist-info
djangocms_attributes_field
djangocms_attributes_field-0.1.1.dist-info
djangocms_column
djangocms_column-1.6.0-py2.7.egg-info
djangocms_googlemap
djangocms_googlemap-0.5.1-py2.7.egg-info
djangocms_inherit
djangocms_inherit-0.2.1-py2.7.egg-info
djangocms_installer-0.8.10-py2.7.egg
djangocms_link
djangocms_link-1.8.1-py2.7.egg-info
djangocms_style
djangocms_style-1.7.0-py2.7.egg-info
djangocms_text_ckeditor
djangocms_text_ckeditor-2.9.3.dist-info
easy-install.pth
easy_install.py
easy_install.pyc
easy_thumbnails
easy_thumbnails-2.3.dist-info
filer
formtools
html5lib
html5lib-0.999999999.dist-info
menus
mptt
pip
pip-8.0.0.dist-info
pkg_resources
polymorphic
pytz-2016.6.1-py2.7.egg
reversion
sekizai
setuptools
setuptools-19.4.dist-info
six-1.10.0-py2.7.egg
tests
treebeard
tzlocal-1.2.2-py2.7.egg
unidecode
webencodings
webencodings-0.5.dist-info
wheel
wheel-0.26.0.dist-info
(test) [jeltoesolnce@twin ~/data/www]%

**Comment by yakky** [comment]
@jeltoesolnce the error in the second run is #270 Fixed in #271
