### ISSUE TITLE
Installation error with ckeditor

### ISSUE THREAD

**Issue by leesolway** [nephila/djangocms-installer#270]
Using the installer in a clean virtualenv:
I am not sure if this is the correct repo to raise the bug in:

Please wait while I install dependencies
Dependencies installed
Creating the project
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/djangocms_text_ckeditor/models.py", line 13, in <module>
    from .html import clean_html, extract_images
  File "/Users/lee/.virtualenvs/example/lib/python2.7/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
ImportError: cannot import name sanitizer
The installation failed.

**Comment by yakky** [comment]
Related to divio/djangocms-text-ckeditor#/335

I will pin the html5lib version in the installer too

**Comment by yakky** [comment]
@leesolway try running installer again. The new versin of ckeditor should fix the issue

**Comment by yakky** [comment]
Fixed in  #271 released in 0.8.11
@leesolway thanks for reporting this
