### ISSUE TITLE
cannot run djangocms -s -f -p . web

### ISSUE THREAD

**Issue by jankrnavek** [nephila/djangocms-installer#288]
djangocms-installer (0.9)
djangocms (3.4.0)
python 3.5.1 (64b)

Here are my commands.

cd /home/webhosting/cms/
/opt/python3/bin/virtualenv env --always-copy
 cd /home/webhosting/cms/; source env/bin/activate;
 pip install djangocms-installer  
djangocms -s -f -p . web

-------------------------------------   ERROR MESSAGE ---------------------------------------
Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying djangocms_video.0001_initial... OK
  Applying djangocms_video.0002_set_related_name_for_cmsplugin_ptr... OK
  Applying djangocms_video.0003_field_adaptions... OK
  Applying djangocms_video.0004_move_to_attributes... OK
  Applying djangocms_video.0005_migrate_to_filer... OK
  Applying djangocms_video.0006_field_adaptions... OK
  Applying djangocms_video.0007_create_nested_plugin... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying menus.0001_initial... OK
  Applying sessions.0001_initial... OK
Creating admin user
/home/webhosting/cms/env/bin/python3.5: can't open file 'create_user.py': [Errno 2] No such file or directory
The installation has failed.

*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/home/webhosting/cms/env/bin/djangocms", line 11, in <module>
    sys.exit(execute())
  File "/home/webhosting/cms/env/lib/python3.5/site-packages/djangocms_installer/main.py", line 41, in execute
    django.setup_database(config_data)
  File "/home/webhosting/cms/env/lib/python3.5/site-packages/djangocms_installer/django/__init__.py", line 394, in setup_database
    create_user(config_data)
  File "/home/webhosting/cms/env/lib/python3.5/site-packages/djangocms_installer/django/__init__.py", line 411, in create_user
    subprocess.check_call([sys.executable, 'create_user.py'], env=env)
  File "/opt/python3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/webhosting/cms/env/bin/python3.5', 'create_user.py']' returned non-zero exit status 2
(env) [root@machine cms]#

**Comment by jankrnavek** [comment]
Sorry for false issue,   command  "djangocms -w web"  is working for me fine.
Hanz
