### ISSUE TITLE
Incorrect time zone settings Ubuntu

### ISSUE THREAD

**Issue by abdelwahebmoalla** [nephila/djangocms-installer#324]
after I followed the tutorial when i wanted to run the project  with python manafe.py runserver i got this exception

Traceback (most recent call last):                                                                                        File "manage.py", line 22, in <module>                                                                                    execute_from_command_line(sys.argv)                                                                                   File "/mnt/c/Users/abdel/Desktop/django_cms/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line                                                                                     utility.execute()                                                                                                     File "/mnt/c/Users/abdel/Desktop/django_cms/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute                                                                                                       settings.INSTALLED_APPS                                                                                               File "/mnt/c/Users/abdel/Desktop/django_cms/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__                                                                                                               self._setup(name)                                                                                                     File "/mnt/c/Users/abdel/Desktop/django_cms/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup                                                                                                                    self._wrapped = Settings(settings_module)                                                                             File "/mnt/c/Users/abdel/Desktop/django_cms/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 137, in __init__                                                                                                                 raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)                                                 ValueError: Incorrect timezone setting: local

**Comment by abdelwahebmoalla** [comment]
I used the last version provided by pip and I executed the command djangocms my_project
I solved the issue by changing local to UTC

**Comment by yakky** [comment]
@abdelwahebmoalla could you test the latest develop to see if the issue is fixed for your previous timezone setting?

thanks

**Comment by yakky** [comment]
closed due to lack of feedback
