### ISSUE TITLE
installation...

### ISSUE THREAD

**Issue by archila1** [nephila/djangocms-installer#374]
soo i'm trying to install djangocms. but! after going through tutorial, i get error on when trying to do migrate.

just going step by step, as in guide.  installing virtualenv, activating, installing djangocms, starting project, making changes to settings.py file, and at last trying to python manage.py migrate.  this is where i get error...

i have Python 3.8 , Django 3.1  djangocms is 3.7?

## Additional information

> (virtenv) PS D:\virtenv\myapp> python .\manage.py migrate
Traceback (most recent call last):
  File ".\manage.py", line 22, in <module>
    main()
  File ".\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\virtenv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\virtenv\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\virtenv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\virtenv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\virtenv\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\virtenv\lib\site-packages\cms\models\__init__.py", line 8, in <module>
    from .placeholderpluginmodel import *  # nopyflakes
  File "D:\virtenv\lib\site-packages\cms\models\placeholderpluginmodel.py", line 3, in <module>
    from cms.models.fields import PlaceholderField
  File "D:\virtenv\lib\site-packages\cms\models\fields.py", line 2, in <module>
    from cms.forms.fields import PageSelectFormField
  File "D:\virtenv\lib\site-packages\cms\forms\fields.py", line 4, in <module>
    from django.forms.fields import EMPTY_VALUES
ImportError: cannot import name 'EMPTY_VALUES' from 'django.forms.fields' (D:\virtenv\lib\site-packages\django\forms\fields.py)

**Comment by kuttamuwa** [comment]
I came across the same error. What we both missed is django version. Django 3.1 is not supported by django-cms. 
See:  http://docs.django-cms.org/en/latest/index.html#requirements

I downgraded django 3.1 to 3.0. Problem was fixed.

**Comment by archila1** [comment]
strange. i think i have django 3.0 at work and it was not working. gonna try again. thx for info
