### ISSUE TITLE
django-cms 3.9.0 is out!

### ISSUE THREAD

**Issue by goutnet** [nephila/djangocms-installer#388]
Hi,

we just released djangoCMS 3.9.0 can you add this new version to the installer?

Thanks!

**Comment by greyhare** [comment]
Django 3.2 is out as well (It's already up to 3.2.5) and djangoCMS 3.9 supports it.

**Comment by speendo** [comment]
Just got in some trouble to update my Docker image because `--django-version 3.2` is not supported...
https://github.com/speendo/djangocms-postgres-docker

**Comment by goutnet** [comment]
@speendo  what command are you trying to run?

**Comment by speendo** [comment]
First I tried to run the installer without specifying the django version:

    djangocms --db postgres://djangocms_db_user:djangocms_db@db:5432/djangocms_db --no-deps --i18n yes --use-tz yes --permissions yes --languages de --languages en --bootstrap yes --starting-page no --parent-dir /app/projects my_djangocms_project

The installer responded with

```
[...]
djangocms-app | Creating the project
djangocms-app | /app/bin/django-admin.py:17: RemovedInDjango40Warning: django-admin.py is deprecated in favor of django-admin.
djangocms-app |   warnings.warn(
djangocms-app | Currently installed Django version 3.2 differs from the declared 3.1. Please check the given `--django-version` installer argument, your virtualenv configuration and any package forcing a different Django version
djangocms-app | Traceback (most recent call last):
djangocms-app |   File "/scripts/runscript.py", line 114, in <module>
djangocms-app |     subprocess.run(django_cms_call, check=True)
djangocms-app |   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
djangocms-app |     raise CalledProcessError(retcode, process.args,
djangocms-app | subprocess.CalledProcessError: Command '['djangocms', '--db', 'postgres://djangocms_db_user:djangocms_db@db:5432/djangocms_db', '--no-deps', '--i18n', 'yes', '--use-tz', 'yes', '--permissions', 'yes', '--languages', 'de', '--languages', 'en', '--bootstrap', 'yes', '--starting-page', 'no', '--parent-dir', '/app/projects', 'my_djangocms_project']' returned non-zero exit status 9.
```

It seems though, that the installation still kind of worked - after the container restarted it applied migrations and started the development server.

So I tried to specify the django-version with

    djangocms --db postgres://djangocms_db_user:djangocms_db@db:5432/djangocms_db --no-deps --i18n yes --use-tz yes --permissions yes --languages de --languages en --bootstrap yes --starting-page no --parent-dir /app/projects --django-version 3.2 my_djangocms_project

That was of course not possible at all:

```
djangocms-app | djangocms: error: argument --django-version: invalid choice: '3.2' (choose from '3.1', '3.0', '2.2', 'stable', 'lts')
djangocms-app | Traceback (most recent call last):
djangocms-app |   File "/scripts/runscript.py", line 115, in <module>
djangocms-app |     subprocess.run(django_cms_call, check=True)
djangocms-app |   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
djangocms-app |     raise CalledProcessError(retcode, process.args,
djangocms-app | subprocess.CalledProcessError: Command '['djangocms', '--db', 'postgres://djangocms_db_user:djangocms_db@db:5432/djangocms_db', '--no-deps', '--i18n', 'yes', '--use-tz', 'yes', '--permissions', 'yes', '--languages', 'de', '--languages', 'en', '--bootstrap', 'yes', '--starting-page', 'no', '--parent-dir', '/app/projects', '--django-version', '3.2', 'my_djangocms_project']' returned non-zero exit status 2.

```

**Comment by speendo** [comment]
I don't want to rush anybody, but are there plans or a road map until when the installer will be updated to django-cms 3.9?

I find the installer to be much more convenient than the manual installation and it's also still listed as "preferred method" on the django-cms website.

However, it's almost a month since django cms 3.9 came out for which the preferred installation method doesn't work yet...

I'm also fine with an answer like "no plans yet". I just want to know if I should rather wait or go for the manual installation.

**Comment by greyhare** [comment]
I'm getting the feeling this installer is abandoned. There has been no activity in all of 2021.

**Comment by mazulo** [comment]
@yakky @protoroto sorry to bother you folks, but do we have any plans on moving the project forward along with the djangocms project?
